# Name of the workflow
name: Pull Request Checker
run-name: Pull Request Checker

# Secrets used in the workflow
# KEY_SSH: SSH key to access the repository (used with deploy keys)
# KEY_GPG: GPG key to sign commits or tags
# GIT_EMAIL: Email address used for git commits

# This workflow will be triggered on pull request to any branch
on:
  pull_request:
    branches:
      - '*'  # Trigger on pull requests to any branch

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      KEY_GPG: ${{ secrets.KEY_GPG }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

  build:
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
      MSSQL_DATABASE: ${{ secrets.MSSQL_DATABASE }}
      MSSQL_USER: ${{ secrets.MSSQL_USER }}
      MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
      STORE_HOST: ${{ secrets.STORE_HOST }}
      STORE_KEY: ${{ secrets.STORE_KEY }}
      STORE_PORT: ${{ secrets.STORE_PORT }}
    
  integration-test:
    needs: build
    uses: ./.github/workflows/integration-test.yml
    with:
      branch: ${{ github.head_ref }}
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      MSSQL_HOST: ${{ secrets.MSSQL_HOST }}
      MSSQL_DATABASE: ${{ secrets.MSSQL_DATABASE }}
      MSSQL_USER: ${{ secrets.MSSQL_USER }}
      MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
      STORE_HOST: ${{ secrets.STORE_HOST }}
      STORE_KEY: ${{ secrets.STORE_KEY }}
      STORE_PORT: ${{ secrets.STORE_PORT }}